name: flutter_figma_test
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  build_runner: ^2.3.2
  http: ^0.13.5
  badges: ^2.0.3
  get_it: ^7.2.0
  flutter_rating_bar: ^4.0.1
  google_nav_bar: ^5.0.6
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  
  assets:
    - assets/

  

  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto-medium.ttf

